version: "3.0"
services:
  hash_to_int:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "hash-to-int"
      MODULE_TYPE: "Processing"
      HOST_NAME: "0.0.0.0"
      HOST_PORT: "9090"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      LOG_LEVEL: "DEBUG"
    ports:
      - 9090:9090
